### ISSUE TITLE
kuma

### ISSUE THREAD

**Issue by mayaaravotwm** [c6o/docs#96] opened 2021-11-08 14:18 UTC
hello,
we have kong ingress as our ingress controller on our aws eks cluster, and kuma as our service mesh.
whenever we intercept or teleport a deployment, we can't access the service from outside, only from the inside. so the internal routes work well but the external don't work. it is relevant to both the original service and the intercepted one as well.
we have kuma sidecar added to each pod in the namespace, your intercepted pod gets it as well.

what can we do?

@c6o/cli/1.1.1 darwin-x64 node-v14.17.3

**Comment by nsainaney** [comment] 2021-11-08 19:44
Duplicate of https://github.com/c6o/roadmap/issues/30. Closing this issue here and we'll follow up there.

Thank you!

**Closed by nsainaney** 2021-11-08 19:44 UTC
Labels: bug
